language: php

php:
  - '7.1'
  
directories:
  - $HOME/.composer/cache/files

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - composer self-update
  - composer install --no-interaction
  - cp .env.travis .env
  - pear install pear/PHP_CodeSniffer
  - phpenv rehash
  - php artisan serve &
  
script:
  - php artisan dusk
  - vendor/bin/phpunit --coverage-text
  - phpcs --ignore=app/Http/Controllers/Auth,app/Http/Controllers/Controller.php app/Http/Controllers